Fandango/urls.py
from django.urls import path

from Fandango.views import (
    AddPegoste, HomePage, PegosteView, Pegostes, UpdatePegoste, Pegosteadores, PegosteadorHome, RedirectSlugPegoste
)


"""
The order of the paths is no accidental.
* <username> in the end is a string, so before evaluating it, check if catalog of Pegosteadores is being call.
* If it is not the catalog of pegosteadores, then proceed to resolve other possibilities.
* Starting with <username>:
  * If no other path is provided, then it will return the "home" page of that user, which will be the last pegoste, 
    if there is any.
  * if "pegostes" comes next, then show all the pegostes created in that blog, if there is any.
  * if "pegoste" comes after <username>, then check:
    * If "add" then display the form to create a pegoste.
    * If it is an ID, then redirect to the slug of that ID.
    * if it is a slug:
        * If "update" comes after the slug, then show the update form.
        * Otherwise, just display the pegoste.  
"""


app_name = 'Fandango'
urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('pegosteadores/', Pegosteadores.as_view(), name='pegosteadores'),
    path('<username>/', PegosteadorHome.as_view(), name='pegosteador_home'),
    path('<username>/pegostes/', Pegostes.as_view(), name='pegostes_list'),
    path('<username>/pegoste/add', AddPegoste.as_view(), name='add_pegoste'),
    path('<username>/pegoste/<int:pk>/', RedirectSlugPegoste.as_view(), name='pegoste_pk'),
    path('<username>/pegoste/<slug:slug>/update', UpdatePegoste.as_view(), name='update_pegoste'),
    path('<username>/pegoste/<slug:slug>/', PegosteView.as_view(), name='pegoste'),
]

Merequetengue/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', TemplateView.as_view(template_name='Merequetengue/about.html'), name='about'),
    path('accounts/', include('accounts.urls')),
    path('', include('Fandango.urls')),
]

# When running development server (default), there is need to add MEDIA_URL explicitly.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterPegosteadorView

# Using defaults in django.settings.
# * When no redirect URL is provided, or settings.LOGIN_URL is not set, settings.LOGIN_URL defaults to '/accounts/login'
#   Reference: https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-LOGIN_URL

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register_pegosteador/', RegisterPegosteadorView.as_view(), name='register_pegosteador'),
]

templates/Merequetengue/about.html
{% extends 'Merequetengue/base_template.html' %}

{% block title %}Who are we?{% endblock %}

{% block content %}
    <p>We are a group (of one person) dedicated to do any kind of thing to get a good grade for delivering this project.</p>
    <p>That is why we called the site "Merequetengue", because the ups and downs of learning Django and its advantages.</p>
    <p>
    "Fandango" is just another kind of merequetengue, so its very suitable for the name of our main application. Also
    because the name describes the plurality of a Blog site, in which many people publishes many topics, which will be
    equivalent to a party (a fandango) with many people talking at the same time about many things.
    </p>
    <p>
    Faithful to Mexican tradition, we are calling our blog posts "Pegostes", which is a kind of messing thing to do,
    thus authors are our "Pegosteadores".
    </p>
    <p>
    Hopefully, you will find this fandango of pegostes in a merequetengue of your liking.
    </p>
    <p>The Team (just me)</p>
{% endblock %}

templates/Merequetengue/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}Let's Fandango!{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top d-flex">
            <div class="d-flex justify-content-between">
                <div class="container">
                        {% if user.is_authenticated %}
                            <a class="btn btn-primary" href="{% url 'Fandango:home' %}">Home</a>
                            <a class="navbar-brand" href="{% url 'Fandango:pegosteador_home' user %}">{{ user }}</a>
                            <a class="btn btn-primary" href="{% url 'accounts:logout' %}">(Logout, d-oh!)</a>
                        {% else %}
                            <a class="btn btn-primary" href="{% url 'Fandango:home' %}">Home</a>
                            <a class="btn btn-primary" href="{% url 'accounts:login' %}">(Yeah, login)</a>
                            <a class="btn btn-primary" href="{% url 'accounts:register_pegosteador' %}">Register</a>
                        {% endif %}
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Welcome to Fandango!</h1>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                {% block recent %}{% endblock %}
            </div>
        </header>
        <!-- Content-->
        {% block content %}

        {% endblock %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="{% url 'about' %}">Who are we?</a>(We are not Batman!)</li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="facebook.com"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="twiteer.com"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="instagram.com"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>

    </body>
</html>